/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class C_in_Java */

#ifndef _Included_C_in_Java
#define _Included_C_in_Java
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     C_in_Java
 * Method:    sum
 * Signature: ([I)I
 */
JNIEXPORT jint JNICALL Java_C_1in_1Java_sum
  (JNIEnv *, jobject, jintArray);

#ifdef __cplusplus
}
#endif
#endif
